# yaml-language-server: $schema=https://json.schemastore.org/github-workflow

name: Coding Standards
on:
  push:
    branches:
      - 'develop'
      - 'trunk'
      - 'master'
  pull_request:
    branches:
      - '**'
  workflow_dispatch:

jobs:
  test:
    name: PHP / PHP ${{ matrix.php }}
    uses: johnbillion/plugin-infrastructure/.github/workflows/reusable-coding-standards.yml@trunk
    strategy:
      matrix:
        php:
          # Newest and oldest supported versions of PHP
          - '8.3'
          - '7.4'
      fail-fast: false
    with:
      php: ${{ matrix.php }}
