# yaml-language-server: $schema=https://json.schemastore.org/github-workflow

name: Integration Tests
on:
  push:
    branches:
      - 'develop'
      - 'trunk'
      - 'master'
  pull_request:
    branches:
      - '**'
  workflow_dispatch:

jobs:
  test:
    name: WP ${{ matrix.wp }} / PHP ${{ matrix.php }}
    uses: johnbillion/plugin-infrastructure/.github/workflows/reusable-integration-tests.yml@trunk
    strategy:
      matrix:
        wp:
          # Latest 3 major versions of WordPress
          - '6.6-RC2'
          - '6.5'
          - '6.4'
        php:
          # Newest and oldest supported versions of PHP
          - '8.3'
          - '7.4'
        include:
          # Oldest supported version of WordPress
          - php: '7.4'
            wp: '5.7'
      fail-fast: false
    with:
      wp: ${{ matrix.wp }}
      php: ${{ matrix.php }}
      node: false
